/** Die Prüfgruppen des Slices an einer Kante: der Runner kennt nur diese Liste. */
export { checkStart } from './check-start.mjs';
export { checkEdgeMaskGroup } from './check-edge-mask.mjs';
export { checkOnboarding, makeOnboardingRun } from './check-onboarding.mjs';
export { checkMining } from './check-mining.mjs';
export { checkHitJuice } from './check-hit-juice.mjs';
export { checkRooting } from './check-rooting.mjs';
export { checkColony } from './check-colony.mjs';
export { checkRaidGroup } from './check-raid-group.mjs';
export { checkStorage } from './check-storage.mjs';
export { checkRaidCap } from './check-raid-cap.mjs';
export { checkSoilMass } from './check-soil-mass.mjs';
export { checkBurrowRing } from './check-burrow-ring.mjs';
export { checkReveal } from './check-reveal.mjs';
export { checkDunglingLook } from './check-dungling-look.mjs';
export { checkFixtures } from './check-fixtures.mjs';
export { checkVerticality } from './check-verticality.mjs';
export { checkVerticalityWiring } from './check-verticality-wiring.mjs';
export { checkActionTypes } from './check-action-types.mjs';
export { checkDeterminism } from './check-determinism.mjs';
export { checkGameClock } from './check-game-clock.mjs';
export { checkStartup } from './check-startup.mjs';
export { checkArchitecture } from './check-architecture.mjs';
export { summary } from './expect.mjs';