/** Every state transition in the slice goes through one of these actions. */

export const ACTION_TYPES = {
  HIVE_CLICKED: 'HIVE_CLICKED',
  HIVE_MUTATION_DONE: 'HIVE_MUTATION_DONE',
  DUNGLING_SPAWNED: 'DUNGLING_SPAWNED',
  TILE_SELECTED: 'TILE_SELECTED',
  ACTION_MENU_CLOSED: 'ACTION_MENU_CLOSED',
  MINING_COMMAND: 'MINING_COMMAND',
  MINING_STARTED: 'MINING_STARTED',
  MINING_TICK: 'MINING_TICK',
  GRID_EXPANDED: 'GRID_EXPANDED',
  BUILD_MENU_SHOWN: 'BUILD_MENU_SHOWN',
  BUILD_MENU_CLOSED: 'BUILD_MENU_CLOSED',
  RESET: 'RESET',
};