/** Die Aktionen, die der zentrale Reducer versteht. */
export const ACTION = Object.freeze({
  HIVE_CLICKED: 'HIVE_CLICKED',
  TILE_SELECTED: 'TILE_SELECTED',
  TILE_SELECTION_CLEARED: 'TILE_SELECTION_CLEARED',
  MINING_ORDERED: 'MINING_ORDERED',

  HIVE_MUTATION_SETTLED: 'HIVE_MUTATION_SETTLED',
  DUNGLING_SPAWNED: 'DUNGLING_SPAWNED',
  DUNGLING_EMERGED: 'DUNGLING_EMERGED',
  DUNGLING_READY: 'DUNGLING_READY',
  DUNGLING_REACHED_TILE: 'DUNGLING_REACHED_TILE',
  MINING_PROGRESS: 'MINING_PROGRESS',
  MINING_COMPLETED: 'MINING_COMPLETED',
  GRID_EXPANDED: 'GRID_EXPANDED',
  BUILD_MENU_SHOWN: 'BUILD_MENU_SHOWN',
  ROOTING_TICK: 'ROOTING_TICK',
  HIVE_TICK: 'HIVE_TICK',

  BUILD_CHOSEN: 'BUILD_CHOSEN',
  BUILDING_PLACED: 'BUILDING_PLACED',
  BUILDING_SELECTED: 'BUILDING_SELECTED',
  BUILDING_DESELECTED: 'BUILDING_DESELECTED',
  WORKER_ASSIGNED: 'WORKER_ASSIGNED',
  WORKER_RELEASED: 'WORKER_RELEASED',

  WORK_TICK: 'WORK_TICK',

  FLOOR_DESCEND: 'FLOOR_DESCEND',

  LAB_OPENED: 'LAB_OPENED',
  LAB_CLOSED: 'LAB_CLOSED',
  STONE_BOUGHT: 'STONE_BOUGHT',
  STONE_PLACED: 'STONE_PLACED',

  MUTANT_CREATED: 'MUTANT_CREATED',
  MUTANT_REVERTED: 'MUTANT_REVERTED',
});
